### ISSUE TITLE
Understanding the cluster permutation results

### ISSUE THREAD

**Issue by GCosme** [smathot/time_series_test#1]
Hello SMathôt.
Thanks for this great and much needed tool.

I am first testing with cluster permutations using the following code:
```
results = tst.lmer_permutation_test(dm,
    'pupil ~ Reward_Condition * Social_Condition * Group',
    groups='ID',
    winlen=100,
    iterations=1,
    cluster_p_threshold=0.05)
```
The results is a dictionary that contains a key for each tested effect, and within each effect, a list. I get the following list for one of the interaction effects (Reward * Group):

`
[(3000, 5900, 3159.205831104706, 0.0),
(9500, 9799, 593.9869462968337, 0.0),
(5900, 7500, 396.47977918794743, 0.0),
 (7500, 9500, 202.3675251768708, 0.0)]
`
Can you elucidate what this list means? How should I interpret this?
Thank you!

**Comment by GCosme** [comment]
I read from the cluster's function:

> 
> Extracts the largest clusters based on a p-threshold of .05 based on a
>     datamatrix as returned by lmer_series(). Returns a dict with effects as
>     keys and a list of (start, end, zsum) tuples as values. The list is sorted
>     by the zsum.

That is straightforward. 
Thank you!

**Comment by smathot** [comment]
Thanks and glad you figured it out. Just for posterity, these tuples are clusters defined by a (start, end, z-sum, hit proportion), which means that the p-value for each cluster is 1 - hit proportion.
